name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: 'Tagged Release'
    runs-on: 'windows-latest'
    permissions:
      contents: write

    steps:
      # ...
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: npm install
        run: |
          npm install

      - name: Test & Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run lint
          npm exec tsc
          npm run package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: 'Wallpaperz - Developed by Oyintare Ebelo'
          draft: true
          files: |
            release/build/*.exe
            release/build/*.blockmap
            release/build/latest.yml
